site_name: ByenatOS Documentation
site_description: ByenatOS 操作系统项目文档
site_author: ByenatOS Team
site_url: https://byenatos.github.io

repo_name: byenatos/byenatos
repo_url: https://github.com/byenatos/byenatos
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex:
      mathjax: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 首页: index.md
  - 架构设计:
    - 系统架构: Architecture/SystemArchitecture.md
    - 详细架构: Architecture/DetailedSystemArchitecture.md
    - 系统边界: Architecture/SystemBoundaries.md
    - LLM驱动架构: Architecture/LLMDriverArchitecture.md
    - 本地模型架构: Architecture/LocalModelArchitecture.md
    - PSP内存管理: Architecture/PSPMemoryManagement.md
    - PSP策略管理: Architecture/PSPStrategyManagement.md
  - API文档:
    - 系统API: APIs/SystemAPIs.md
    - HiNATA定义: APIs/HiNATADefinition.md
    - HiNATA格式: APIs/HiNATAFormat.md
    - HiNATA处理: APIs/HiNATAProcessing.md
    - 注意力权重系统: APIs/AttentionWeightSystem.md
    - PSP迭代: APIs/PSPIteration.md
  - 开发者指南:
    - 应用开发指南: DeveloperGuide/AppDevelopmentGuide.md
    - 系统集成指南: Integration/SystemIntegrationGuide.md
    - 开发者生态系统: DeveloperEcosystem/DeveloperProgram.md
  - 用户指南:
    - 用户界面: UserInterface/
  - 项目文档:
    - 贡献指南: CONTRIBUTING.md
    - 行为准则: CODE_OF_CONDUCT.md
    - 治理文档: GOVERNANCE.md
    - 变更日志: CHANGELOG.md
    - 开源转型总结: OPENSOURCE_TRANSFORMATION_SUMMARY.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/byenatos/byenatos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/byenatos
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 